mlflow server --host 127.0.0.1 --port 7000

In [2]:
import pandas as pd
# Import data
data = pd.read_csv('Sleep_health_and_lifestyle_dataset.csv')
data

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Heart Rate,Daily Steps,Sleep Disorder
0,Male,27,Software Engineer,6.1,6,42,6,Overweight,77,4200,None
1,Male,28,Doctor,6.2,6,60,8,Normal,75,10000,None
2,Male,28,Doctor,6.2,6,60,8,Normal,75,10000,None
3,Male,28,Sales Representative,5.9,4,30,8,Obese,85,3000,Sleep Apnea
4,Male,28,Sales Representative,5.9,4,30,8,Obese,85,3000,Sleep Apnea
...,...,...,...,...,...,...,...,...,...,...,...
369,Female,59,Nurse,8.1,9,75,3,Overweight,68,7000,Sleep Apnea
370,Female,59,Nurse,8.0,9,75,3,Overweight,68,7000,Sleep Apnea
371,Female,59,Nurse,8.1,9,75,3,Overweight,68,7000,Sleep Apnea
372,Female,59,Nurse,8.1,9,75,3,Overweight,68,7000,Sleep Apnea
373,Female,59,Nurse,8.1,9,75,3,Overweight,68,7000,Sleep Apnea

In [18]:
from pycaret.classification import *
import pandas as pd
import mlflow
from mlflow.models import infer_signature

# Set URI for MLflow tracking server
mlflow.set_tracking_uri(uri="http://127.0.0.1:7000")

# Set experiment name
mlflow.set_experiment("Mlflow w9")

# Import data
data = pd.read_csv('Sleep_health_and_lifestyle_dataset.csv')

# Filter data to include only the desired features
desired_features = ['Gender', 'Age', 'Occupation', 'Sleep Duration', 'Quality of Sleep',
                   'Physical Activity Level', 'Stress Level', 'BMI Category', 'Heart Rate', 'Daily Steps']
data = data[desired_features + ['Sleep Disorder']]

# Initialize PyCaret setup with desired features
s = setup(data, target='Sleep Disorder', 
        #   ignore_features=['Gender', 'Age', 'Occupation'],  # Ignoring the non-desired features
          bin_numeric_features=['Gender', 'Quality of Sleep', 'Physical Activity Level', 'Stress Level', 'BMI Category'])

# pca=True, pca_components=10
# Compare models
best = compare_models()

# Tune the best performing model
tuned_model = tune_model(best)

# Evaluate the model
evaluate_model(tuned_model)

# Finalize the model for deployment
final_model = finalize_model(tuned_model)

# Save the finalized model
save_model(final_model, 'sleep_disorder_classification_model')

# Enable autologging
mlflow.autolog()

# Start a new MLflow run
with mlflow.start_run():
    # Log the trained model
    mlflow.sklearn.log_model(final_model, "sleep_disorder_classification_model")

2024/04/27 18:03:18 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '5f86c58c90b645989dbdb254a425693b', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow
2024/04/27 18:03:18 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\bayuk\AppData\Local\Programs\Python\Python310\lib\site-packages\mlflow\utils\autologging_utils\safety.py:556: ConvergenceWarning: Number of distinct clusters (2) found smaller than n_clusters (5). Possibly due to duplicate points in X."
2024/04/27 18:03:18 WARNING mlflow.sklearn: Training metrics will not be recorded because training labels were not specified. To automatically record training metrics, provide training labels as inputs to the model training function.
2024/04/27 18:03:22 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '165fa78a0bde4af9ab1581cd2e6324b2', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow
2024/04/27 18:03:22 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\bayuk\AppData\Local\Programs\Python\Python310\lib\site-packages\mlflow\utils\autologging_utils\safety.py:556: ConvergenceWarning: Number of distinct clusters (4) found smaller than n_clusters (5). Possibly due to duplicate points in X."
2024/04/27 18:03:22 WARNING mlflow.sklearn: Training metrics will not be recorded because training labels were not specified. To automatically record training metrics, provide training labels as inputs to the model training function.
2024/04/27 18:03:28 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'dc744fe7cdb148fba10195edc08aa9b8', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow
2024/04/27 18:03:28 WARNING mlflow.sklearn: Training metrics will not be recorded because training labels were not specified. To automatically record training metrics, provide training labels as inputs to the model training function.
2024/04/27 18:03:33 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'b973437001e142138a6b4ff7967ec143', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow
2024/04/27 18:03:33 WARNING mlflow.sklearn: Training metrics will not be recorded because training labels were not specified. To automatically record training metrics, provide training labels as inputs to the model training function.

2024/04/27 18:04:34 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'df6312bf71484beb9d3c2630ce74b337', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow
2024/04/27 18:04:45 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\bayuk\AppData\Local\Programs\Python\Python310\lib\site-packages\mlflow\types\utils.py:394: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."

Fitting 10 folds for each of 10 candidates, totalling 100 fits

2024/04/27 18:04:56 WARNING mlflow.sklearn.utils: Failed to autolog metrics for RandomizedSearchCV. Logging error: This RandomizedSearchCV instance was initialized with `refit=False`. predict is available only after refitting on the best parameters. You can refit an estimator manually using the `best_params_` attribute
2024/04/27 18:04:57 WARNING mlflow.sklearn.utils: _get_classifier_artifacts.<locals>.plot_confusion_matrix failed. The artifact training_confusion_matrix will not be recorded. Artifact error: This RandomizedSearchCV instance was initialized with `refit=False`. predict is available only after refitting on the best parameters. You can refit an estimator manually using the `best_params_` attribute
2024/04/27 18:04:57 WARNING mlflow.sklearn.utils: BaseSearchCV.score failed. The 'training_score' metric will not be recorded. Scoring error: This RandomizedSearchCV instance was initialized with `refit=False`. score is available only after refitting on the best parameters. You can refit an estimator manually using the `best_params_` attribute
2024/04/27 18:04:57 WARNING mlflow.sklearn: Failed to infer model signature: the trained model does not have a `predict` or `transform` function, which is required in order to infer the signature
2024/04/27 18:04:57 WARNING mlflow.sklearn: Model was missing function: predict. Not logging python_function flavor!
2024/04/27 18:05:10 INFO mlflow.sklearn.utils: Logging the 5 best runs, 5 runs will be omitted.

Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelinâ€¦

Transformation Pipeline and Model Successfully Saved

2024/04/27 18:06:17 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
2024/04/27 18:06:17 INFO mlflow.tracking.fluent: Autologging successfully enabled for statsmodels.
2024/04/27 18:06:17 INFO mlflow.tracking.fluent: Autologging successfully enabled for lightgbm.
2024/04/27 18:06:17 INFO mlflow.tracking.fluent: Autologging successfully enabled for xgboost.

In [21]:
import pandas as pd
import mlflow.pyfunc

# Load the model
logged_model = 'runs:/f08030755a614cc8b3bf4ba09f065fab/model'
loaded_model = mlflow.pyfunc.load_model(logged_model)

# Input data
data = {
    'Gender': [1.0],  # Male=1.0, Female=0.0
    'Age': [35.0],
    'Occupation_Engineer': [1.0],
    'Occupation_Nurse': [0.0],
    'Occupation_Lawyer': [0.0],
    'Occupation_Salesperson': [0.0],
    'Occupation_Teacher': [0.0],
    'Occupation_Manager': [0.0],
    'Occupation_Software Engineer': [0.0],  
    'Occupation_Doctor': [0.0],
    'Occupation_Accountant': [0.0],
    'Occupation_Scientist': [0.0],
    'Occupation_Sales Representative': [0.0],
    'Sleep Duration': [7.0],
    'Quality of Sleep': [3.0],
    'Physical Activity Level': [2.0],
    'Stress Level': [4.0],
    'BMI Category_Normal': [1.0],  
    'BMI Category_Overweight': [0.0],
    'BMI Category_Normal Weight': [0.0],
    'BMI Category_Obese': [0.0],
    'Heart Rate': [70.0],
    'Daily Steps': [8000.0]
}

input_data = pd.DataFrame(data)

# Predict
predictions = loaded_model.predict(input_data)
print(predictions)

Downloading artifacts:   0%|          | 0/9 [00:00<?, ?it/s]

[1]